"""create assets table

Revision ID: 4g3940909310
Revises: 3f2839808209
Create Date: 2025-01-27 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4g3940909310'
down_revision: Union[str, None] = '3f2839808209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('event_registration_id', sa.String(length=20), nullable=False),
    sa.Column('asset_url', sa.String(length=500), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_registration_id'], ['event_registrations.event_registration_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###