"""create event_registration table

Revision ID: 3f2839808209
Revises: 2e1828707108
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2839808209'
down_revision: Union[str, None] = '2e1828707108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_registrations',
    sa.Column('event_registration_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('season', sa.String(length=100), nullable=False),
    sa.Column('artwork_count', sa.Integer(), nullable=False),
    sa.Column('registration_status', sa.String(length=50), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_dt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_registration_id')
    )
    op.create_index(op.f('ix_event_registrations_event_registration_id'), 'event_registrations', ['event_registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_registrations_event_registration_id'), table_name='event_registrations')
    op.drop_table('event_registrations')
    # ### end Alembic commands ###